/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lcq_com_androidtest_agcTest */

#ifndef _Included_lcq_com_androidtest_agcTest
#define _Included_lcq_com_androidtest_agcTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lcq_com_androidtest_agcTest
 * Method:    initAgcMod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lcq_com_androidtest_agcTest_initAgcMod
  (JNIEnv *, jobject);

/*
 * Class:     lcq_com_androidtest_agcTest
 * Method:    agcFrame
 * Signature: ([SI[S)I
 */
JNIEXPORT jint JNICALL Java_lcq_com_androidtest_agcTest_agcFrame
  (JNIEnv *, jobject, jshortArray, jint, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
