/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lcq_com_androidtest_VoiceMixUtil */

#ifndef _Included_lcq_com_androidtest_VoiceMixUtil
#define _Included_lcq_com_androidtest_VoiceMixUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lcq_com_androidtest_VoiceMixUtil
 * Method:    mixData
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_lcq_com_androidtest_VoiceMixUtil_mixData
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

JNIEXPORT jint JNICALL Java_lcq_com_androidtest_VoiceMixUtil_getSize
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     lcq_com_androidtest_VoiceMixUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lcq_com_androidtest_VoiceMixUtil_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
